name: Laravel Styleguide Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Install host app
      run: composer create-project --prefer-dist laravel/laravel host

    - name: Checkout the package
      uses: actions/checkout@v2
      with:
        path: host/packages/xpersonas/laravel-styleguide

    - name: Verify package location
      working-directory: ./host
      run: ls -la packages/xpersonas

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Install Dependencies
      working-directory: ./host/packages/xpersonas/laravel-styleguide
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      working-directory: ./host/packages/xpersonas/laravel-styleguide
      run: ./vendor/bin/phpunit --testdox

    - name: PHPCS Code Quality
      working-directory: ./host/packages/xpersonas/laravel-styleguide
      run: ./vendor/bin/phpcs --ignore=node_modules,vendor,tests,database,*.blade.php --standard=PSR2 --extensions=php .
